name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
          - uses: webfactory/ssh-agent@v0.5.4
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Cache Yocto downloads
            uses: actions/cache@v3
            with:
            path: build/downloads
            key: downloads-${{ runner.os }}-${{ hashFiles('conf/**') }}
            restore-keys: |
            downloads-${{ runner.os }}-

          - name: Cache Yocto sstate-cache
            uses: actions/cache@v3
            with:
            path: build/sstate-cache
            key: sstate-${{ runner.os }}-${{ hashFiles('conf/**') }}
            restore-keys: |
            sstate-${{ runner.os }}-
          - name: Run build
            timeout-minutes: 2160
            run: |
               docker run --rm \
                 -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
                 -e GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:24-assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./build.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
          - name: Run full test
            timeout-minutes: 2160
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./full-test.sh
